$(document).ready(function(){
  $('.menu-img').click(function(){
    console.log('test');
    $('.slider-menu').slideToggle();
  })
  $('.close-menu').click(function(){
    console.log('test');
    $('.slider-menu').slideUp();
  })
})
